name: CI Deploy Node app on AWS Elastic Beanstalk

env:
  APP_NAME: face-similarity-api
  APP_ENV_NAME: Facesimilarityapi-env
  AWS_REGION: us-east-1

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
        node-version: 14.x
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
    - name: Install dependencies
      run: yarn
      
    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**"
      
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.APP_NAME }}
        environment_name: ${{ env.APP_ENV_NAME }}
        version_label: ${{env.APP_NAME}}-${{ steps.format-time.outputs.replaced }}
        region: ${{ env.AWS_REGION }}
        deployment_package: deploy.zip
